[tool.black]
line-length = 100
target-version = ['py39']

[tool.isort]
known_first_party = ["app"]
line_length = 100
profile = "black"
remove_redundant_aliases = true

[tool.pylint.main]
extension-pkg-whitelist = ["pydantic"]

[tool.pylint.format]
max-line-length = 100
expected-line-ending-format = "LF"
